src/RegionAwareApp/Models/ErrorViewModel.cs
using System;

namespace RegionAwareApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/RegionAwareApp/Controllers/DiagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace RegionAwareApp.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class DiagController : ControllerBase
    {
        // GET: api/Diag
        [HttpGet]
        public ActionResult<string> Get()
        {
            var diagConfig = Environment.GetEnvironmentVariable("DIAG") ?? "OK";

            if (diagConfig.Equals("KO",StringComparison.InvariantCultureIgnoreCase))
            {
                return new StatusCodeResult(503);
            }

            return "Diag OK";
        }
    }
}

src/RegionAwareApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RegionAwareApp.Models;

namespace RegionAwareApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public static uint IndextHits { get; set; }

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            IndextHits++;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/RegionAwareApp/Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace RegionAwareApp.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class LabController : Controller
    {
        private readonly ILogger<LabController> _logger;

        public LabController(ILogger<LabController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var labConfig = Environment.GetEnvironmentVariable("LAB_EXPERIMENT") ?? "0";

            if (labConfig.Equals("1", StringComparison.InvariantCultureIgnoreCase))
            {
                return ExperimentalFeature();
            }

            return GoodOldAlg();
        }

        private IActionResult GoodOldAlg()
        {
            return View();
        }

        private IActionResult ExperimentalFeature()
        {
            DateTime now = DateTime.Now;
            while (DateTime.Now < now.AddSeconds(2))
            {

            }
            return View();
        }

        private long FindPrimeNumber(int n)
        {
            int count = 0;
            long a = 2;
            while (count < n)
            {
                long b = 2;
                int prime = 1;// to check if found a prime
                while (b * b <= a)
                {
                    if (a % b == 0)
                    {
                        prime = 0;
                        break;
                    }
                    b++;
                }
                if (prime > 0)
                {
                    count++;
                }
                a++;
            }
            return (--a);
        }

    }
}

src/RegionAwareApp/Controllers/TopSecretController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RegionAwareApp.Models;

namespace RegionAwareApp.Controllers
{
    [Authorize]

    public class TopSecretController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public TopSecretController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
         
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/RegionAwareApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <h2 class="display-3">This instance is running in:</h2>
        <h2 class="display-3">@(Environment.GetEnvironmentVariable("REGION_NAME") ?? "Local")</h2>
        <h2 class="display-3">@(Environment.MachineName ?? "No machine name ")</h2>
        
        <p>Hits count: @(RegionAwareApp.Controllers.HomeController.IndextHits)</p>
        
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>

src/RegionAwareApp/Views/Lab/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Lab Index</h1>

src/RegionAwareApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RegionAwareApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RegionAwareApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lab" asp-action="Index">Lab Fast/Slow</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TopSecret" asp-action="Index">Top Secret</a>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RegionAwareApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/RegionAwareApp/Views/TopSecret/Index.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>Super top secret page</h1>